version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"


python:
  install:
    - requirements: ci/rtd-requirements.txt
    - path: .

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
